name: Dockerize docker-age
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v4
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: kyotokodocker/docker-age
        tags: latest, distroless-debian_agev1.1.1