name: Dockerize docker-age
on:
  push:
    branches:
      - main
      - github-action-ci-2
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: cat env
      run: source .env && echo "TAG_PREFIX=$tag_prefix" >> $GITHUB_ENV && echo "IMAGE=$image" >> $GITHUB_ENV && echo "AGE_VERSION=$age_version" >> $GITHUB_ENV
    - name: see env again
      run: echo "IMAGE=${{ env.IMAGE }}"
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Publish to Docker Hub
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: kyotokodocker/docker-age:latest, kyotokodocker/docker-age:distroless-debian_agev1.1.1 
